export const userConstants = {
    LOGIN_REQUEST:'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE:'USER_LOGIN_FAILURE',
    REGISTER_FAILURE:'REGISTER_FAILURE',
    CLEANING_MESSAGE:'USER_CLEANING_MESSAGE',
    FORGOTTEN_PASSWORD_FAILURE:'USER_FORGOTTEN_PASSWORD_FAILURE',
    VALIDATION:'USER_VALIDATION'
};